### PR TITLE
Update library.json

### PR DESCRIPTION
**Pull request by ivankravets**
https://github.com/platformio/platformio-atom-ide/issues/415

### CODE REVIEW

**Comment by euphi** [comment]
HomieNodeCollection is incompatible with Homie-1.5.0. It requieres 2.x, which unfortunately is not yet available on platformio.

As a workaround, I `git clone` Homie into a subdirectory of the `lib` path.

**Comment by euphi** [comment]
Oh.. any help to improve the situation is welcome :-)

**Comment by ivankravets** [comment]
A library can depend on VCS repository. See http://docs.platformio.org/en/latest/librarymanager/config.html#dependencies

**Comment by euphi** [comment]
I changed library.json dependency to:

```
{
                        "name": "Homie",
                        "version": "https://github.com/marvinroger/homie-esp8266.git#develop"
}
```

This accesses the latest version of Homie. Unfortunately there aren't any tags yet for the 2.0 release.

**Pull request closed without merging**
